### ISSUE TITLE
Problem with processing mode GPU

### ISSUE THREAD

**Issue by hgzik** [vvvv/VL.Devices.AzureKinect.Body#1]
I have a problem with VL.Devices.AzureKinect.Body.1.2.1. When I open the help patch "Track bodies" the camera starts for a second but then shuts down again and vvvv freezes. The problem seems to be with the connection to the GPU. If I change the processing mode in the "Body Tracker" node to CPU and the frame rate in the "AzureKinect" node to 5fps, I get an output, but the CPU cooling then runs at full speed.

I am using an RTX 3080 with driver 472.84 (also tried 472.12). Azure Kinect Body Tracking SDK 1.1.0 (also tried 1.1.1) is installed on the default path. The Body Tracking Viewer works without errors. vvvv-version: 2021.4.8

**Comment by joreg** [comment]
please note there are newer versions of the nuget available as preview! for GPU you'll need those plus:
- Cuda 11.4
- BodyTracking SDK 1.1.0 (in the default install path)

hope this helps.

**Comment by hgzik** [comment]
Thank you very much! I was not familiar with installing pre-release versions until now. Now the BodyTracker works as expected.
